import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { GuideWindow } from './components/GuideWindow/GuideWindow';
import './styles/app-theme.css';
import './styles/base.css';
import 'katex/dist/katex.min.css';
// The built-in fonts, so presets render correctly on Windows, which doesn't ship these families.
// Generated by `pnpm fonts:css`; only the Latin (and, for Arabic fonts, Arabic) files are bundled.
import '@/styles/fonts.css';
import { emitAppReady } from './lib/tauri';

if (import.meta.env.DEV) {
  // Dev-only handles for driving the app from the browser console / automated checks.
  void Promise.all([
    import('./store/document'),
    import('./store/settings'),
    import('./store/view'),
    import('./store/style'),
    import('./store/tabs'),
    import('./markdown/render'),
  ]).then(([doc, settings, view, style, tabs, render]) => {
    (window as unknown as { __mdv: unknown }).__mdv = {
      document: doc.useDocumentStore,
      settings: settings.useSettingsStore,
      view: view.useViewStore,
      style: style.useStyleStore,
      tabs: tabs.useTabsStore,
      render: render.renderMarkdown,
    };
  });
}

// The guide window (see `guide.rs`) loads this same page with a `#guide` marker.
const isGuideWindow = window.location.hash === '#guide';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>{isGuideWindow ? <GuideWindow /> : <App />}</React.StrictMode>,
);

// The app itself calls emitAppReady once settings/styles are loaded and any launch
// file is open, so the window only appears once it's actually themed correctly. This
// is just a safety net in case that never happens (e.g. an error during startup).
// The guide window has its own reveal, and must never trigger the main window's.
if (!isGuideWindow) setTimeout(emitAppReady, 1500);
